# Generated by Django 3.2.6 on 2021-09-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_excape_cafe_name', models.CharField(max_length=200)),
                ('room_excape_cafe_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_excape_theme_name', models.CharField(max_length=200)),
                ('room_excape_theme_value', models.CharField(max_length=200)),
                ('room_excape_cafe_price', models.CharField(max_length=200)),
                ('room_excape_cafe_etc1', models.CharField(max_length=200)),
                ('room_excape_cafe_etc2', models.CharField(max_length=200)),
                ('room_excape_cafe_etc3', models.CharField(max_length=200)),
                ('room_excape_cafe_etc4', models.CharField(max_length=200)),
                ('room_excape_cafe_etc5', models.CharField(max_length=200)),
                ('re_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.recafe')),
            ],
        ),
        migrations.CreateModel(
            name='ReTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_excape_time_name', models.CharField(max_length=200)),
                ('room_excape_time_value', models.CharField(max_length=200)),
                ('re_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.retheme')),
            ],
        ),
    ]
